- ros_topic_name: /imu/data_raw
  gz_topic_name: /model/picar2/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /scan
  gz_topic_name: /model/picar2/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS

- ros_topic_name: /ld07/scan
  gz_topic_name: /model/picar2/ld07_scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS

- ros_topic_name: /imu/mag
  gz_topic_name: /model/picar2/mag
  ros_type_name: sensor_msgs/msg/MagneticField
  gz_type_name: gz.msgs.Magnetometer
  direction: GZ_TO_ROS

- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
