from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import Command, EqualsSubstitution, LaunchConfiguration
from launch_ros.actions import ComposableNodeContainer, Node
from launch_ros.descriptions import ComposableNode
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    desc_share    = Path(get_package_share_directory('picar2_description'))
    bringup_share = Path(get_package_share_directory('picar2_bringup'))

    port_arg  = DeclareLaunchArgument('port',  default_value='/dev/ttyYahboom0')
    baud_arg  = DeclareLaunchArgument('baud',  default_value='460800')
    lidar_arg = DeclareLaunchArgument(
        'lidar', default_value='lds02rr',
        description='LiDAR model: lds02rr | ld19 | none')
    use_mag_arg = DeclareLaunchArgument('use_mag', default_value='false',
                                        description='Enable magnetometer fusion in Madgwick filter')
    calib_arg = DeclareLaunchArgument(
        'calib_file',
        default_value=str(bringup_share / 'config' / 'imu_calib.yaml'),
        description='imu-calib-ros calibration file (gyro + accel bias/scale)')

    robot_description = ParameterValue(
        Command([
            'xacro ', str(desc_share / 'urdf' / 'picar2.urdf.xacro'),
            ' port:=', LaunchConfiguration('port'),
            ' baud:=', LaunchConfiguration('baud'),
            ' lidar:=', LaunchConfiguration('lidar'),
        ]),
        value_type=str)

    controllers_yaml = str(bringup_share / 'config' / 'controllers.yaml')

    def lidar_is(model):
        return IfCondition(EqualsSubstitution(LaunchConfiguration('lidar'), model))

    # controller_manager loads the hardware plugin and runs the control loop
    ros2_control_node = Node(
        package='controller_manager',
        executable='ros2_control_node',
        parameters=[
            {'robot_description': robot_description},
            controllers_yaml,
        ],
        output='both',
    )

    # robot_state_publisher converts joint_states → TF
    robot_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        parameters=[{'robot_description': robot_description}],
    )

    # Spawners — retry until controller_manager is up
    jsb_spawner = Node(
        package='controller_manager',
        executable='spawner',
        arguments=['joint_state_broadcaster', '--controller-manager-timeout', '30'],
    )

    ackermann_spawner = Node(
        package='controller_manager',
        executable='spawner',
        arguments=['ackermann_steering_controller', '--controller-manager-timeout', '30'],
    )

    cmd_vel_relay = Node(
        package='picar2_bringup',
        executable='cmd_vel_relay.py',
        name='cmd_vel_relay',
        output='screen',
    )

    ekf_node = Node(
        package='robot_localization',
        executable='ekf_node',
        parameters=[str(bringup_share / 'config' / 'ekf.yaml')],
        remappings=[('/odometry/filtered', '/odom')],
    )

    # Apply gyro/accel calibration (bias + scale) before Madgwick filtering.
    # Calibration file generated by: ros2 run imu_calib do_calib
    imu_calib = Node(
        package='imu_calib',
        executable='apply_calib_node',
        parameters=[{
            'calib_file':       LaunchConfiguration('calib_file'),
            'calibrate_gyros':  True,
            'gyro_calib_samples': 100,
        }],
        remappings=[
            ('raw',       '/imu/data_raw'),
            ('corrected', '/imu/data_corrected'),
        ],
    )

    imu_filter = Node(
        package='imu_filter_madgwick',
        executable='imu_filter_madgwick_node',
        parameters=[{
            'use_mag': LaunchConfiguration('use_mag'),
            'publish_tf': False,
            'world_frame': 'enu',
        }],
        remappings=[
            ('/imu/data_raw', '/imu/data_corrected'),
            ('/imu/mag',      '/imu/mag'),
        ],
    )

    # ── LiDAR: lds02rr (Neato XV-11 / LDS02RR, GPIO motor PWM) ──────────────
    lidar_lds02rr = Node(
        package='picar2_lidar',
        executable='lidar_node',
        name='lidar_node',
        output='screen',
        condition=lidar_is('lds02rr'),
        parameters=[{
            'target_rpm':   300.0,
            'angle_offset': -2.77,
        }],
    )

    # ── LiDAR: ld19 (LDRobot LD19, lifecycle composable node) ────────────────
    # Uses picar2_bringup/config/lidar_ld19.yaml (serial port: /dev/ldlidar).
    # Skips ldlidar_node's own robot_state_publisher — picar2 already has one.
    lidar_ld19_config = str(bringup_share / 'config' / 'lidar_ld19.yaml')

    lidar_ld19_container = ComposableNodeContainer(
        name='lidar_container',
        namespace='',
        package='rclcpp_components',
        executable='component_container_isolated',
        composable_node_descriptions=[
            ComposableNode(
                package='ldlidar_component',
                plugin='ldlidar::LdLidarComponent',
                name='lidar_node',
                parameters=[lidar_ld19_config],
                extra_arguments=[{'use_intra_process_comms': True}],
            ),
        ],
        output='screen',
        condition=lidar_is('ld19'),
    )

    lidar_ld19_lc_mgr = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lidar_lifecycle_manager',
        output='screen',
        condition=lidar_is('ld19'),
        parameters=[{
            'autostart':  True,
            'node_names': ['lidar_node'],
        }],
    )

    # ── LD07 structured-light depth sensor — always on, front of car ─────────
    # Publishes /ld07/scan in ld07_link frame. Serial port: /dev/ld07 (udev).
    ld07_node = Node(
        package='ldrobot_ld07',
        executable='ldrobot_ld07_node',
        output='screen',
        parameters=[
            str(Path(get_package_share_directory('ldrobot_ld07')) / 'params' / 'ld07.yaml')
        ],
    )

    return LaunchDescription([
        port_arg,
        baud_arg,
        lidar_arg,
        use_mag_arg,
        calib_arg,
        ros2_control_node,
        robot_state_publisher,
        jsb_spawner,
        ackermann_spawner,
        cmd_vel_relay,
        imu_calib,
        imu_filter,
        ekf_node,
        lidar_lds02rr,
        lidar_ld19_container,
        lidar_ld19_lc_mgr,
        ld07_node,
    ])
